export const TEXT = {
  common: {
    appName: 'Cook Helper',
    save: '保存',
    cancel: '取消',
    delete: '删除',
    edit: '编辑',
    add: '添加',
    search: '搜索',
    confirm: '确认',
    back: '返回',
    loading: '加载中...',
    noData: '暂无数据',
    success: '操作成功',
    error: '操作失败',
    demoMode: 'Demo 模式不可写',
  },
  nav: {
    recommend: '智能推荐',
    inventory: '食材管理',
    utensils: '厨具管理',
    recipes: '菜谱管理',
    calendar: '烹饪日历',
    demo: '体验 Demo',
    login: '登录',
    register: '注册',
    logout: '退出登录',
  },
  inventory: {
    title: '食材管理',
    categories: {
      vegetable: '蔬菜',
      meat: '肉类',
      egg_dairy_bean: '蛋奶豆制品',
      staple: '主食/干货',
      seasoning: '调料',
    },
    stockLevel: {
      enough: '充足',
      low: '不多了',
      out: '完全没了',
    },
    addIngredient: '添加食材',
    editIngredient: '编辑食材',
    updateStock: '更新库存',
    batchUpdate: '批量更新',
  },
  utensils: {
    title: '厨具管理',
    addUtensil: '添加厨具',
    name: '名称',
    note: '备注',
  },
  recipes: {
    title: '菜谱管理',
    addRecipe: '新增菜谱',
    recipeDetail: '菜谱详情',
    ingredients: '主要食材',
    auxiliaryIngredients: '辅助食材',
    seasonings: '所需调料',
    utensils: '所需厨具',
    steps: '烹饪步骤',
    cookTime: '烹饪时间',
    difficulty: '难度',
    photos: '成品照片',
    tips: '备注/Tips',
    attributes: {
      method: '烹饪方式',
      spiciness: '辣度',
      greasiness: '油腻度',
      flavor: '咸鲜甜',
      dietType: '荤素',
      nutrition: '主打营养',
      scene: '适合场景',
      cuisine: '菜系',
    },
  },
  calendar: {
    title: '烹饪日历',
    addEntry: '记录烹饪',
    planEntry: '计划做菜',
    completed: '我做完了',
    updateStock: '更新食材库存',
  },
  recommend: {
    title: '今日推荐',
    tiers: {
      can_make_now: '现在就能做',
      need_shopping: '需额外购买',
      clear_stock: '清库存推荐',
    },
    filters: '筛选条件',
    shoppingList: '购物清单',
    selectRecipes: '选择想做的菜',
    generateList: '生成购物清单',
    checkout: '采购完成',
  },
  auth: {
    login: '登录',
    register: '注册',
    email: '邮箱',
    password: '密码',
    confirmPassword: '确认密码',
    verifyCode: '验证码',
    sendCode: '发送验证码',
    loginSuccess: '登录成功',
    registerSuccess: '注册成功',
    logoutSuccess: '已退出登录',
    loginTitle: '登录 Cook Helper',
    registerTitle: '注册 Cook Helper',
    hasAccount: '已有账号？',
    goLogin: '去登录',
    noAccount: '没有账号？',
    goRegister: '去注册',
    codeSentTo: '验证码已发送到 {email}，请查看邮箱',
    verify: '验证',
    fillInfo: '填写信息',
    verifyEmail: '验证邮箱',
    emailRequired: '请输入邮箱',
    emailInvalid: '邮箱格式不正确',
    passwordRequired: '请输入密码',
    passwordMin: '密码至少6位',
    confirmPasswordRequired: '请确认密码',
    passwordMismatch: '两次密码不一致',
    otpRequired: '请输入6位验证码',
    loginFailed: '登录失败',
    registerFailed: '注册失败',
    verifyFailed: '验证失败',
    loggingIn: '登录中...',
    registering: '注册中...',
    verifying: '验证中...',
  },
  demo: {
    title: '交互体验 Demo',
    description: '这是一个功能演示页面，除写入操作外所有功能均可体验。',
    readOnly: 'Demo 模式下不可写入',
  },
};
